metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml

reload.enabled: true
reload.period: 600s

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
setup.kibana:

output.elasticsearch:
  hosts: ["192.168.8.11:9201"]
  username: "elastic"
  password: "changeme"
setup.kibana:
  host: "192.168.8.11:5602"
  
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

